NRI課題、CSS部分のPull Request
kamdam13/Tomohiro-Kanda pull request #2
Opened 2020-04-01 10:18 UTC by kamdam13

# nri/css/style.css のレビューお願いします！
## やったこと
- b6261aa までのコミットでcssの実装をしました。
- b712e85 のコミットでmargin,paddingの指定を見直しました。
- 0e55603 のコミットでheaderの上部固定を実装しました。

2020-04-03 03:34 UTC, piasoratech requested changes
![image](https://user-images.githubusercontent.com/57445698/78321527-3789fe00-75a7-11ea-8b96-124269d0bfba.png)
上記部分の`Share`の文字サイズ小さくしましょう

![image](https://user-images.githubusercontent.com/57445698/78321577-58525380-75a7-11ea-8b00-ddb25ce96ad4.png)
上記部分の表示が本家と異なるので直しましょう

あと.vscodeや.DS_Storeがプルリクに含まれているので、それは除外しましょう。
除外の仕方は「.gitignore 書き方」などで調べれば出てくるので挑戦してみてください

2020-04-03 06:13 UTC, kamdam13 commented
## 修正のコミットを行いました
- 16dd0b6 のコミットで.gitignoreを設定して不要なファイルを除外しました
- f4d7566 のコミットでフォントのfamily,size,weightなどの調整を行いました
- 7b7a3fd のコミットでchervronの設定を変更して本家の見た目に近づけました
- 011f7f3 のコミットでmarginの調整を行い本家の見た目に近づけました

2020-04-06 07:01 UTC, piasoratech requested changes
以前コメントした部分が直っていないように思えます。
FollowUsより下部分は本家と比べて左に寄っているように見えますが、そちらではそう見えないでしょうか？
また、NRIの強みの各要素はホバーすると>が消えてしまうのでその部分を修正しましょう！
![image](https://user-images.githubusercontent.com/57445698/78531144-d6b92a80-781f-11ea-8e49-ba9aedd648a8.png)

2020-04-07 06:27 UTC, kamdam13 commented
## prを修正しました
- ade2d09 のコミットでfooterのレイアウトを調整しました
- edfaf2c のコミットでhover時の意図しない動作を修正しました
- eea0f02 のコミットでheaderのレイアウトを調整しました

作業時の画面幅が適切でなくレイアウトのズレに気がついてませんでした……

2020-04-08 02:52 UTC, piasoratech approved these changes
良いかと！

2020-04-08 02:58 UTC, merged