家具屋課題html部分
kamdam13/Tomohiro-Kanda pull request #4
Opened 2020-04-09 02:37 UTC by kamdam13

# index.htmlのレビューをお願いします
## やったこと
- 8646506 までのコミットで全体のコーディングを終わらせました
- 81226b3 のコミットで画像の整理とパスの変更,srcsetの漏れを修正しました
- 26b9e10 のコミットで空白がspaceでなくtabだった箇所を修正しました

2020-04-09 09:50 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-09 09:50 UTC, piasoratech commented on kaguya/css/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
このCSSはどっから持ってきたんでしょうか？
内容を理解されているのであれば特に問題ありませんが、書いてある内容が何をしているのか分からないようであれば理解するようにしていただきたいです。

2020-04-09 09:50 UTC, piasoratech commented on kaguya/index.html
> +					<li><a href="#">CONTACT</a></li>
ここは今後作成するページにリンク先が貼ってあるはずなので#ではない指定でお願いします。
(現段階で正常に遷移する必要はないです。)

2020-04-09 09:50 UTC, piasoratech commented on kaguya/index.html
> +					<p>私たちは、家具を売るのではなく、お客様の理想とする <br>「暮らし」を提案します。<br> 仕事で疲れた後に帰りたくなる、<br> 今日も１日頑張ろうと思える、<br> そんな空間をお客様と一緒に作り上げていくのが私たちの仕事です。</p>
これさすがに見にくいのでコード内で改行してほしいです…

2020-04-09 09:50 UTC, piasoratech commented on kaguya/index.html
> +					<li><a href="#">アームストロングのチェア入荷</a></li>
文面違いますね

2020-04-09 09:50 UTC, piasoratech commented on kaguya/index.html
> +					<textarea name="comment" id="comment" cols="30" rows="10"></textarea>
フォーム内に表示されている文字列がないです

2020-04-09 09:50 UTC, piasoratech commented on kaguya/index.html
> +		</section>
`h1`タグ内容に対しての入れ子情報ではないので、このタグの終わりは`h1`の終わりにしましょう

2020-04-09 09:50 UTC, piasoratech commented on kaguya/index.html
> +				<li><a href="#">CONTACT</a></li>
ここもヘッダーと同じ修正をしておいてください

2020-04-09 09:50 UTC, piasoratech commented on kaguya/index.html
> +		<address>&copy;HTMLCSS.code</address>
コピーライトは`address`タグを使用しないです。
(HTML4まではこの表記でした。)

2020-04-10 08:47 UTC, kamdam13 commented
# prを修正しました
## やったこと
- headerとfooterにリンクを正しく記載しました
- formにplaceholderを設定しました
- 文面の誤植を修正しました
- アウトラインの構造を変更しました
- footerのコピーライトのタグをaddressから変更しました
- header-logoの仕様にないaタグを外しました

normalize.cssは https://necolas.github.io/normalize.css/ よりダウンロードして使用しています。
全部の仕様を把握しているわけではありませんが、使用しないでcssをコーディングしていない際に`input[type="search"]`にcssが適応されなかったことがあり、個別に`-webkit-appearance:none`を指定すれば解決できましたがnormalize.cssがそれを解決していること。sanitize.cssが全要素に`box-sizing:border-box`を適応していることと比べ、レイアウトに大きく影響する値が設定されていないことよりnormalize.cssを採用しています。

2020-04-13 03:23 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-13 03:23 UTC, piasoratech commented on kaguya/index.html
> +			<h1>NEWS</h1>
`h1`タグを複数使うのは良くないので、ここは`h2`にしたほうが良いかと。
これ以降の同じような要素も同様です。
(いろんな意見はありますが…)

2020-04-13 05:15 UTC, kamdam13 commented
# prを修正しました
## やったこと
- 0be10af のコミットでh1タグを1つ除いてh2タグに変更しました

2020-04-13 07:11 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-04-13 15:08 UTC, merged