家具屋課題,
kamdam13/Tomohiro-Kanda pull request #5
Opened 2020-04-09 08:09 UTC by kamdam13

2020-04-09 15:41 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
共通する部分はコメントがなくても修正してください。

2020-04-09 15:41 UTC, piasoratech commented on kaguya/template/index.html
> +<!DOCTYPE html>
このファイルってどういった意図で作成しました？

2020-04-09 15:41 UTC, piasoratech commented on kaguya/contact/index.html
> +					</form>
インデントあってないです

2020-04-09 15:41 UTC, piasoratech commented on kaguya/contact/index.html
> +						<input type="submit" value="SEND">
ここもインデントあってないです

2020-04-09 15:41 UTC, piasoratech commented on kaguya/contact/index.html
> +		<address>&copy;HTMLCSS.code</address>
HTML5ではコピーライトマークを`address`タグで囲わなくなったので、調べて修正してください。

2020-04-09 15:41 UTC, piasoratech commented on kaguya/news/index.html
> +						<li><a href="#">アームストロングのチェア入荷</a></li>
見本と文面違います

2020-04-14 06:17 UTC, kamdam13 commented
# prを修正しました
## やったこと
- 5274868 のコミットでmasterをrebaseしました
- 全ファイルでインデントをtabからspaceに変更しました
- 85ec8e7 のコミットでcontact,news,recruitのヘッダー、フッターを修正しました
- contact,news,recruitのアウトラインを修正しました

templateディレクトリは新規ページを作成する際に、相対パスを変更し新規ページと同じディレクトリ構造となっている物があると便利であると本にあり、なるほど便利であると思ったので同様に作成しました。contact,news,recruitページを作成した時点で課題の上では不要なものですが、作成するページが増えた際やheader,footerを書き換えたいときに残っていると便利だなと思ったので残してあります

2020-04-14 06:23 UTC, piasoratech approved these changes
良いかと！
テンプレートファイルはその用途であればローカルで保存をしておくなどしてください。
少なくともPRに含めるべきものではないです。

2020-04-14 06:28 UTC, merged