Kaguya/css home
kamdam13/Tomohiro-Kanda pull request #6
Opened 2020-04-17 08:52 UTC by kamdam13

# 家具屋課題topページのcssのレビューをお願いします
## やったこと
- index.htmlの修正
- - innnerの幅を固定するためのブロックを追加しました
- - fontawosomeでchevronを追加しました
- - news部分をfigure>img+figcaptionに変更しました

- css/style.cssのコーディング

2020-04-17 09:23 UTC, piasoratech requested changes
・選択されていないページの文字色が見本は変わっているので確認してください。
![image](https://user-images.githubusercontent.com/57445698/79553906-347b2b80-80d8-11ea-8db6-33065dffbcfc.png)
・view moreの文字色も見本に合わせましょう。不透明度もXDで確認ができます。
![image](https://user-images.githubusercontent.com/57445698/79553932-452ba180-80d8-11ea-91de-4f748745e67d.png)

2020-04-17 09:23 UTC, piasoratech commented on kaguya/index.html
> +        <a href="#">view more <i class="fas fa-chevron-right"></i></a>
NEWSページへのリンクを付けておいてください

2020-04-17 09:23 UTC, piasoratech commented on kaguya/index.html
> +        <a href="#">view more <i class="fas fa-chevron-right"></i></a>
RECRUITページへのリンクを付けておいてください

2020-04-17 09:50 UTC, kamdam13 commented
# prを修正しました
## やったこと
- htmlのaタグのリンク先を修正しました
- headerのaタグや本文のaタグの文字色が異なっている箇所を修正しました

2020-04-20 02:38 UTC, choimake reviewed
前回の指摘漏れで申し訳ありません。
商品画像内の「アームストロングの...」の文言が半透明になっています。
XDのデータを見る限り透明度は指定されていないので、XDのデータに準拠した透明度に修正をお願いします。

提出してもらったページ
<img width="1160" alt="スクリーンショット 2020-04-20 11 34 21" src="https://user-images.githubusercontent.com/52233450/79708702-1f321700-82fb-11ea-8e4c-d11b8e871c9e.png">

XD
<img width="859" alt="スクリーンショット 2020-04-20 11 34 35" src="https://user-images.githubusercontent.com/52233450/79708865-9cf62280-82fb-11ea-99c1-a05d3a32914b.png">

2020-04-20 02:45 UTC, kamdam13 commented
# prを修正しました
## やったこと
- 1b59a4d のコミットでnewsのfigcaptionの透明度を修正しました

2020-04-20 03:16 UTC, choimake commented
申し訳ありません。
1件指摘もれがありましたので、そちらの修正もお願いいたします。

以下画像のメニューの「アームストロング...」の文言のstyleに「text-shadow」が適応されていません。
<img width="842" alt="スクリーンショット 2020-04-20 12 14 32" src="https://user-images.githubusercontent.com/52233450/79710624-8a321c80-8300-11ea-914b-d562944f26dc.png">

XDのデータを確認し、XDで適応されている「text-shadow」のstyleを反映してください。

2020-04-20 03:22 UTC, kamdam13 commented
# prを修正しました
## やったこと
- 9cadf48 のコミットでnewsのfigcaptionにtext-shadowを適応しました

2020-04-20 03:28 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-20 03:28 UTC, piasoratech commented on kaguya/css/style.css
> +	font-family: 'Noto Sans JP',sans-serif;
フォントが違うのでXDで確認してみましょう

2020-04-20 03:41 UTC, kamdam13 commented
# prを修正しました
## やったこと
- c26ab5c のコミットでfontをNoto Sans JPからNoto Sansに変更しました

2020-04-20 03:48 UTC, choimake commented
すいません、1件指摘漏れです。

headerのロゴが表示されていないので、修正お願いします。
<img width="1064" alt="スクリーンショット 2020-04-20 12 47 49" src="https://user-images.githubusercontent.com/52233450/79712179-29591300-8305-11ea-8c81-c14b77006258.png">

2020-04-20 04:00 UTC, kamdam13 commented
# prを修正しました
## やったこと
- header-logoのsrcset 2xのパスを修正しました

2020-04-20 04:59 UTC, choimake commented
修正ありがとうございました。
LGTMです！

2020-04-21 15:09 UTC, merged